### ISSUE TITLE
Question about the code (and complaint about open source)

### ISSUE THREAD

**Issue by cylian914** [rimpy-custom/RimPy#131] opened 2023-03-19 20:15 UTC
Hi, there is somthing i don't understand, why having an app that bloated, as i can see it use JS, probably electron to run it and qt, why do you need  that much, and i don't even talk about all the dll/.so needed to run it ?

Also you said previsouly https://github.com/rimpy-custom/RimPy/issues/79  that you can do great thing with the app, but why you don't want to put the source code in github, are you afraid of someone stealing your code or somthing ? Like all the argument you said previsously was "No need to do that" (https://github.com/rimpy-custom/RimPy/issues/79#issuecomment-1212818601). Making it open source will only reduce the work you have to done to have the app working and will be better for all the user.

Pls respond with ARGUMENT not just "i don't need it" because you are not all the player who use it
Thx have a great day

**Comment by char-cole** [comment] 2023-04-08 16:08
after reading the owner's previous responses I find this extremely suspicious and I'm no longer interested in using the app.

**Comment by ForeverZer0** [comment] 2023-04-20 20:14
I am really glad that I read this issue and and the related comments before using this project. I find the responses from the developer extremely concerning, the likes of which I have never before seen in the public coder community. This is complete with deleting the replies of others and locking a topic, as if this is Reddit or some other social media site, and not a more "professional" forum where that behavior is nearly unheard of.

I was interested in using, but was surprised by the significant bloat of the download for such a relatively simple project. That was it, there was no other motive behind my initial issue checking. I had already implemented much of the functionality of this project in a personal bash script that was about 1 kb, and was merely looking for a more robust solution with a graphical front-end. I then noticed that there was no source code available to even determine what the bloat was, paired with dodgy replies and unnecessary defensiveness about it when the issue was politely mentioned. 

Hard pass for me.

**Comment by AldebaraanMKII** [comment] 2023-04-24 23:38
The app uses 10-20% of my gpu (1660s) unless it's minimized. Unless the author is really bad at coding there's something else going on here.

Edit: When it's open and i'm using another program the usage jumps to 80%.

**Comment by twstagg** [comment] 2023-04-29 02:38
No self promotion here pls

**Comment by rimpy-custom** [comment] 2023-06-02 12:54
That is a duplicate of #79 , no need to create new issues just to post your opinions for this project. Question was already answered. Reasoning was given in mentioned topic. There is one thing I can add - the size. App is self-contained, so it has all dependencies provided. It needs qt, js for GUI and downloader functionality. The most heavy is qt part. Thank you for your time,

**Closed as completed by rimpy-custom** 2023-06-02 12:54 UTC
Labels: duplicate
