### ISSUE TITLE
A weird crach when hitting [Download with SteamCMD] botton, in download page of Rimmu-Nation²

### ISSUE THREAD

**Issue by alreShan** [rimpy-custom/RimPy#78] opened 2022-08-07 10:14 UTC
Please check the screenshot picture first.
![#2022-8-7 180654](https://user-images.githubusercontent.com/104878767/183285904-b499f9f6-1d11-494d-b86f-7503564a2174.png)
When hitting the [Download with SteamCMD], RimPy crash without any feed back. But what's weird, is that I tried hit the botton in others mod page, and RimPy works fine.
The mod's page link:
https://steamcommunity.com/sharedfiles/filedetails/?id=2563507593&searchtext=Rimmu-Nation²

The version of RimPy is 1.25.21
![#2022-8-7 181643](https://user-images.githubusercontent.com/104878767/183286153-329dbcf7-cda1-4e0d-9e00-b48ab1eb722f.png)
 
===========================Split line=======================================
#2022-8-7    205845
I found out that, this crash happens in 1.2.5.21, but not in RimPy 1.2.6.25,, and triger in a particular way.

Link1: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2563507593&searchtext=RH2
Link2:
https://steamcommunity.com/sharedfiles/filedetails/?id=2563507593&searchtext=%5BRH2%5D+Rimmu-Nation%C2%B2

Both the links are directing to the same [Steam Workshop Mod Page]. Opening the mod page by paste the link into the [adress bar](screenshot) , then clicking [Download with SteamCMD] botton,, use link1 will not crash but link2 will.
![image](https://user-images.githubusercontent.com/104878767/183292382-fdd0527f-b601-4a2c-b407-f40a880de214.png)

The point is the difference of the links.
[searchtext=RH2] is not crashing, while [searchtext=%5BRH2%5D+Rimmu-Nation%C2%B2] do.

**Comment by rimpy-custom** [comment] 2022-08-07 10:56
Do you get that issue with latest DEV build of RImPy?

**Comment by alreShan** [comment] 2022-08-07 12:38
Haven't tried. I will try it now.

**Comment by alreShan** [comment] 2022-08-07 12:57
OK. I have found the way to reproduce this issue.
I writing it out now.
I think it's a minor bug. Doesn't really harm the using experience.

**Comment by rimpy-custom** [comment] 2022-08-07 13:36
May you be more specific, please? Does issue fixed with latest DEV build? If not, then provide steps to reproduce issue.

**Comment by alreShan** [comment] 2022-08-07 13:47
Yes, it's fixed with latest DEV build. Although it's not that good using experience in latest DEB build :X
But hey! Really appreaciate developing RimPy :D 👍

**Comment by alreShan** [comment] 2022-08-07 13:48
I have added more details in the text content in the last part, splitted by line.

**Comment by rimpy-custom** [comment] 2022-08-07 13:51
If issue fixed in DEV build, then I am closing it for now since no reason to fix what has been already fixed. Thank you for heads up.

**Closed as completed by rimpy-custom** 2022-08-07 13:51 UTC
Labels: more data needed
