### ISSUE TITLE
1.2.6.27 - Clicking strip mods crashes rimpy

### ISSUE THREAD

**Issue by Billiamson** [rimpy-custom/RimPy#96] opened 2022-10-23 06:14 UTC
On rimpy newest version 1.2.6.27 and rimworld 1.4.
Whenever I click on "Strip Mods' the loading dialog will pop up and then rimpy will crash. Looking at the crashlog it always ends with the following: 
INFO:root:Mods added to QTreeWidgets
CRITICAL:root:Exception
Traceback (most recent call last):
  File "F:\Rimpy\rimpy.py", line 3167, in <lambda>
  File "F:\Rimpy\rimpy.py", line 833, in __init__
  File "F:\Rimpy\rimpy.py", line 874, in populate
  File "F:\Rimpy\rimpy.py", line 958, in get_outdated
AttributeError: 'NoneType' object has no attribute 'find_all'

I can upload the full crashlog if needed.

**Comment by rimpy-custom** [comment] 2022-10-23 08:20
Known bug, will be fixed in next release. Just do not want to push updates too frequently. In case of fast fix - open `LoadFolders.xml` in mod folder of `Vanilla Factions Expanded - Classical` and replace `<LoadFolders>` tag with `<loadFolders`>, `</LoadFolders>` with `</loadFolders>`.
XML is casesensitive and according to manual from game devs it should be `<loadFolders>`, but looks like game does not care so RimPy will follow that in next release.

**Comment by Billiamson** [comment] 2022-10-23 21:37
Renaming the tags didn't fix the issue for me. Of course there might be another mod with the same problem but I don't know how to locate it without going through every mod xml one by one. Will just wait for the next release.

Edit: Never mind I looked through 4 folders and found it, Vanilla Backgrounds Expanded is the other problem mod. Rimpy no longer crashing for me.

**Comment by JohnC0de** [comment] 2022-10-26 17:25
What i did was:
- Open the Rimworld mods folder with VSCode and use `Find in files` function on command palette to find all wrong case sensitive lines and used the regex replace to easily fix them.

![image](https://user-images.githubusercontent.com/88864312/198094207-13bb1608-5f78-4eaa-99f8-034bdec2f07e.png)

**Comment by Apklittledog** [comment] 2022-11-10 19:16
> What i did was:
> 
> * Open the Rimworld mods folder with VSCode and use `Find in files` function on command palette to find all wrong case sensitive lines and used the regex replace to easily fix them.
> 
> ![image](https://user-images.githubusercontent.com/88864312/198094207-13bb1608-5f78-4eaa-99f8-034bdec2f07e.png)

I can confirm that i followed these steps and it works. Looks like with about 100 mods installed it was only Simple Sidearms still using the capital L for load. All the rest were lower case. I changed the case on that and Rimpy was happy to strip

**Comment by kimern88** [comment] 2022-11-15 16:07
Have the same issue, however the "Strip Mods" function will still crash rimpy after replacing every occurance of `<LoadFolders>` and `</LoadFolders>`. Are you aware of other xml tags that might be incorrect and cause issues?

**Comment by kimern88** [comment] 2022-11-15 17:29
> Have the same issue, however the "Strip Mods" function will still crash rimpy after replacing every occurance of `<LoadFolders>` and `</LoadFolders>`. Are you aware of other xml tags that might be incorrect and cause issues?

It was `[LC] Consolidated Traits`, "F" not capitalized in loadfolders.xml `<loadfolders>` `</loadfolders>`

**Comment by rimpy-custom** [comment] 2022-11-17 02:14
should be fixed now

**Closed as completed by rimpy-custom** 2022-11-17 02:14 UTC
Labels: bug, next build
